<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-U49T2LA" failures="1" tests="2" name="Try Catch Test " time="0.028" errors="0" timestamp="2021-02-21T22:17:46 IST">
  <testcase classname="TestNGLearning.TestCase4TryCatch" name="doUserReg" time="0.003">
    <failure type="java.lang.AssertionError" message="Test Case failed">
      <![CDATA[java.lang.AssertionError: Test Case failed
at TestNGLearning.TestCase4TryCatch.doUserReg(TestCase4TryCatch.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- doUserReg -->
  <testcase classname="TestNGLearning.TestCase4TryCatch" name="doUserReg2" time="0.009"/>
</testsuite> <!-- Try Catch Test  -->
